
TOKEN = "5714065120:AAEsHdaKkKcZUNv3qSmlBw3g4s0qcyjM4OM"
MYSQL_USER = "root"
MYSQL_PASSWWORD ="password"
MYSQL_DATABASE = "emoji_db"
MYSQL_HOST = "localhost"

MYSQL_URL = "mysql+pymysql://{MYSQL_USER}:{MYSQL_PASSWORD}@{MYSQL_HOST}/{MYSQL_DATABASE}"






REDIS_HOST = "127.0.0.1"
REDIS_PORT = 6379